"""
Step 1: Cotton synthetic data purge — one-time data integrity correction.

What this script does:
  1. NULLs out ice_futures_near/3m/6m/9m/12m and contango_signal on every row
     where is_real_futures_data is False or NULL.
  2. Sets data_quality_tier = 'synthetic_legacy' on those rows.
  3. Sets data_quality_tier = 'spot_only' on rows where FRED spot is real but
     no real ICE futures ever existed (origin-specific rows — Australia, Brazil,
     China, India, Pakistan, West Africa, US).
  4. Logs a before/after summary.

What this does NOT touch:
  - spot_price (FRED PCOTTINDUSDM — this is real market data, keep it)
  - wasde_forecast, wasde_ending_stocks, wasde_su_ratio_pct (USDA — real)
  - The single ICE No.2 Global row with is_real_futures_data=True

Why: 5,626 rows have fabricated ICE futures curves generated by S/U-calibration
scripts. The model must never train on these as if they were real contract prices.
A NULL is correct. A synthetic price is a lie that corrupts every weight it touches.

Run once, then never run again. Once real ICE backfill is complete, this is
permanently replaced in the record by real data or honest NULLs.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone

from database.base import SessionLocal

logger = logging.getLogger(__name__)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)

# Origins that will never have ICE futures — mark spot_only not synthetic_legacy
# (their spot prices are real FRED data; futures were never appropriate for them)
ORIGIN_SPECIFIC_COUNTRIES = {
    "Australia", "Brazil", "China", "India",
    "Pakistan", "West Africa", "US",
}


def run_purge() -> None:
    import sqlite3
    conn = sqlite3.connect("artemis.db")
    cur = conn.cursor()

    # Before counts
    total = cur.execute("SELECT COUNT(*) FROM cotton").fetchone()[0]
    synthetic = cur.execute(
        "SELECT COUNT(*) FROM cotton WHERE is_real_futures_data=0 OR is_real_futures_data IS NULL"
    ).fetchone()[0]
    real = total - synthetic

    logger.info("=== COTTON SYNTHETIC PURGE ===")
    logger.info("Before: total=%d | real=%d | synthetic=%d", total, real, synthetic)

    # Step 1a: NULL out fabricated futures on origin-specific rows
    # These never had real ICE data — mark spot_only
    cur.execute("""
        UPDATE cotton SET
            ice_futures_near  = NULL,
            ice_futures_3m    = NULL,
            ice_futures_6m    = NULL,
            ice_futures_9m    = NULL,
            ice_futures_12m   = NULL,
            contango_signal   = NULL,
            data_quality_tier = 'spot_only',
            updated_at        = CURRENT_TIMESTAMP
        WHERE origin_country IN ('Australia','Brazil','China','India','Pakistan','West Africa','US')
          AND (is_real_futures_data = 0 OR is_real_futures_data IS NULL)
    """)
    origin_rows = cur.rowcount
    logger.info("Origin-specific rows NULLed and marked spot_only: %d", origin_rows)

    # Step 1b: NULL out fabricated futures on any remaining non-real rows
    # (catches historical_fallback rows for ICE No.2 Global if any)
    cur.execute("""
        UPDATE cotton SET
            ice_futures_near  = NULL,
            ice_futures_3m    = NULL,
            ice_futures_6m    = NULL,
            ice_futures_9m    = NULL,
            ice_futures_12m   = NULL,
            contango_signal   = NULL,
            data_quality_tier = 'synthetic_legacy',
            updated_at        = CURRENT_TIMESTAMP
        WHERE origin_country NOT IN ('Australia','Brazil','China','India','Pakistan','West Africa','US')
          AND origin_country != 'ICE No.2 Global'
          AND (is_real_futures_data = 0 OR is_real_futures_data IS NULL)
    """)
    other_rows = cur.rowcount
    logger.info("Other non-real rows marked synthetic_legacy: %d", other_rows)

    # Step 1c: Purge the SYNTHETIC status row in commodity_futures
    cur.execute("""
        UPDATE commodity_futures SET
            ice_cotton_2_3m  = NULL,
            ice_cotton_2_6m  = NULL,
            ice_cotton_2_9m  = NULL,
            ice_cotton_2_12m = NULL,
            status           = 'SYNTHETIC_PURGED'
        WHERE status = 'SYNTHETIC'
    """)
    futures_purged = cur.rowcount
    logger.info("Synthetic commodity_futures rows purged: %d", futures_purged)

    conn.commit()

    # After counts
    real_after = cur.execute(
        "SELECT COUNT(*) FROM cotton WHERE is_real_futures_data=1"
    ).fetchone()[0]
    spot_only = cur.execute(
        "SELECT COUNT(*) FROM cotton WHERE data_quality_tier='spot_only'"
    ).fetchone()[0]
    synth_legacy = cur.execute(
        "SELECT COUNT(*) FROM cotton WHERE data_quality_tier='synthetic_legacy'"
    ).fetchone()[0]
    null_tier = cur.execute(
        "SELECT COUNT(*) FROM cotton WHERE data_quality_tier IS NULL"
    ).fetchone()[0]

    logger.info("=== AFTER PURGE ===")
    logger.info("  Real ICE data:        %d rows", real_after)
    logger.info("  spot_only:            %d rows (FRED spot real, no ICE contracts)", spot_only)
    logger.info("  synthetic_legacy:     %d rows (should be 0 if all origins accounted for)", synth_legacy)
    logger.info("  tier=NULL (new rows): %d rows", null_tier)

    # Verify spot prices are intact
    spot_intact = cur.execute(
        "SELECT COUNT(*) FROM cotton WHERE spot_price IS NOT NULL"
    ).fetchone()[0]
    wasde_intact = cur.execute(
        "SELECT COUNT(*) FROM cotton WHERE wasde_su_ratio_pct IS NOT NULL"
    ).fetchone()[0]
    logger.info("  FRED spot prices intact: %d rows", spot_intact)
    logger.info("  WASDE S/U ratios intact: %d rows", wasde_intact)

    conn.close()
    logger.info("Purge complete. Futures fields NULLed. Spot and WASDE data preserved.")


if __name__ == "__main__":
    run_purge()
