"""add_tier2_fields_to_retailer_intelligence_extract

Revision ID: 063deaba26fb
Revises: 274a2b22c326
Create Date: 2026-06-07 22:53:47.322019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '063deaba26fb'
down_revision: Union[str, Sequence[str], None] = '274a2b22c326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retailer_intelligence_extract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('speaker', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_forward_looking', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('contains_number', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('number_mentioned', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('time_period_referenced', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('affected_decision', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('time_horizon', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('historical_pattern_found', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('similar_prior_quarter', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('similar_prior_language', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('observed_outcome', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pattern_confidence', sa.Numeric(precision=4, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retailer_intelligence_extract', schema=None) as batch_op:
        batch_op.drop_column('pattern_confidence')
        batch_op.drop_column('observed_outcome')
        batch_op.drop_column('similar_prior_language')
        batch_op.drop_column('similar_prior_quarter')
        batch_op.drop_column('historical_pattern_found')
        batch_op.drop_column('time_horizon')
        batch_op.drop_column('affected_decision')
        batch_op.drop_column('time_period_referenced')
        batch_op.drop_column('number_mentioned')
        batch_op.drop_column('contains_number')
        batch_op.drop_column('is_forward_looking')
        batch_op.drop_column('speaker')

    # ### end Alembic commands ###
