"""add_updated_at_reference_tables

Revision ID: 0688d6224451
Revises: caab5ea51fcf
Create Date: 2026-06-09 12:33:50.553076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0688d6224451'
down_revision: Union[str, Sequence[str], None] = 'caab5ea51fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geopolitical_risk_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    with op.batch_alter_table('government_export_incentive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    with op.batch_alter_table('marine_insurance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    with op.batch_alter_table('shipping_lane_risk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    with op.batch_alter_table('us_import_duty_rate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('us_import_duty_rate', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('shipping_lane_risk', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('marine_insurance', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('government_export_incentive', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('geopolitical_risk_event', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
