"""add_updated_at_to_carrier_bid

Revision ID: 0f5b3ec355dd
Revises: 50ce31a57e66
Create Date: 2026-06-07 09:50:46.214834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f5b3ec355dd'
down_revision: Union[str, Sequence[str], None] = '50ce31a57e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carrier_bid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carrier_bid', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
