"""add_retailer_financials_and_intelligence_extract

Revision ID: 274a2b22c326
Revises: 5bc90f28931e
Create Date: 2026-06-07 22:07:26.588611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '274a2b22c326'
down_revision: Union[str, Sequence[str], None] = '5bc90f28931e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retailer_financials',
    sa.Column('retailer_financials_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('retailer_id', sa.Integer(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('period_end_date', sa.Date(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('apparel_revenue_usd', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('apparel_revenue_pct_total', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('apparel_yoy_growth_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('total_net_sales_usd', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('comparable_sales_growth_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('digital_comp_sales_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('gross_margin_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('gross_margin_change_bps', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('sga_rate_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('operating_margin_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('inventory_usd', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('inventory_days', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('store_count_total', sa.Integer(), nullable=True),
    sa.Column('store_count_net_change', sa.Integer(), nullable=True),
    sa.Column('ecommerce_penetration_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('guidance_sales_direction', sa.String(length=50), nullable=True),
    sa.Column('guidance_sales_range_low', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('guidance_sales_range_high', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('guidance_eps_low', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('guidance_eps_high', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('source_10q_url', sa.String(length=500), nullable=True),
    sa.Column('source_8k_url', sa.String(length=500), nullable=True),
    sa.Column('xbrl_extracted', sa.Boolean(), nullable=True),
    sa.Column('manually_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('retailer_financials_id')
    )
    op.create_table('retailer_intelligence_extract',
    sa.Column('extract_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('retailer_id', sa.Integer(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('period_end_date', sa.Date(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('document_section', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('signal_category', sa.String(length=100), nullable=True),
    sa.Column('raw_text_passage', sa.Text(), nullable=True),
    sa.Column('extracted_signal', sa.String(length=500), nullable=True),
    sa.Column('signal_sentiment', sa.String(length=20), nullable=True),
    sa.Column('signal_strength', sa.String(length=20), nullable=True),
    sa.Column('artemis_implication', sa.String(length=500), nullable=True),
    sa.Column('extraction_model', sa.String(length=100), nullable=True),
    sa.Column('extraction_prompt_ver', sa.String(length=20), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('human_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('extract_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retailer_intelligence_extract')
    op.drop_table('retailer_financials')
    # ### end Alembic commands ###
