"""initial_schema_all_tables

Revision ID: 50ce31a57e66
Revises: 
Create Date: 2026-06-07 09:47:55.204824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ce31a57e66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('air_freight',
    sa.Column('air_freight_id', sa.Integer(), nullable=False),
    sa.Column('rate_per_kg', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('key_corridors', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('air_freight_id')
    )
    op.create_table('carrier',
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('carrier_name', sa.String(length=255), nullable=True),
    sa.Column('carrier_type', sa.String(length=50), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('operating_routes', sa.String(length=255), nullable=True),
    sa.Column('certifications', sa.String(length=255), nullable=True),
    sa.Column('reliability_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_transit_days', sa.Integer(), nullable=True),
    sa.Column('contact_primary', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('joined_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('carrier_id')
    )
    op.create_table('carrier_bid',
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('rate_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('transit_days', sa.Integer(), nullable=True),
    sa.Column('vessel_schedule', sa.String(length=255), nullable=True),
    sa.Column('validity_hours', sa.Integer(), nullable=True),
    sa.Column('bid_status', sa.String(length=50), nullable=True),
    sa.Column('bid_timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('bid_id')
    )
    op.create_table('carrier_network',
    sa.Column('carrier_network_id', sa.Integer(), nullable=False),
    sa.Column('receives_rfqs', sa.Boolean(), nullable=True),
    sa.Column('submits_bids', sa.Boolean(), nullable=True),
    sa.Column('wins_contracts', sa.Boolean(), nullable=True),
    sa.Column('total_carriers', sa.Integer(), nullable=True),
    sa.Column('ocean_carriers', sa.Integer(), nullable=True),
    sa.Column('drayage_carriers', sa.Integer(), nullable=True),
    sa.Column('intermodal_carriers', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('carrier_network_id')
    )
    op.create_table('cmt_factories',
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('location_country', sa.String(length=100), nullable=True),
    sa.Column('location_city', sa.String(length=100), nullable=True),
    sa.Column('capacity_pieces_month', sa.Integer(), nullable=True),
    sa.Column('utilisation_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('order_book_depth_weeks', sa.Integer(), nullable=True),
    sa.Column('certifications', sa.String(length=255), nullable=True),
    sa.Column('on_time_delivery_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('lead_time_weeks', sa.Integer(), nullable=True),
    sa.Column('financing_rate_annual_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('platform_verified', sa.Boolean(), nullable=True),
    sa.Column('active_importer_count', sa.Integer(), nullable=True),
    sa.Column('supply_chain_finance_eligible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('factory_id')
    )
    op.create_table('commodity_futures',
    sa.Column('commodity_futures_id', sa.Integer(), nullable=False),
    sa.Column('ice_cotton_2_spot', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ice_cotton_2_3m', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ice_cotton_2_6m', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ice_cotton_2_9m', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ice_cotton_2_12m', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ocean_freight_ffa', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('commodity_futures_id')
    )
    op.create_table('commodity_risk_in_open_programs',
    sa.Column('output_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('corridor', sa.String(length=100), nullable=True),
    sa.Column('commodity_exposure_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cotton_sensitivity_10pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('freight_sensitivity_10pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('fx_sensitivity_5pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_risk_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('risk_rating', sa.String(length=50), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('output_id')
    )
    op.create_table('competitor_factory_intel',
    sa.Column('output_id', sa.Integer(), nullable=False),
    sa.Column('factory_name', sa.String(length=255), nullable=True),
    sa.Column('gaining_from_importer', sa.String(length=255), nullable=True),
    sa.Column('volume_trend', sa.String(length=255), nullable=True),
    sa.Column('corridors_active', sa.String(length=255), nullable=True),
    sa.Column('qualify_recommended', sa.Boolean(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('output_id')
    )
    op.create_table('consignee',
    sa.Column('consignee_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('sourcing_country_mix', sa.String(length=255), nullable=True),
    sa.Column('monthly_volume', sa.String(length=255), nullable=True),
    sa.Column('yoy_origin_shift', sa.String(length=255), nullable=True),
    sa.Column('new_factory_relationships', sa.Integer(), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('consignee_id')
    )
    op.create_table('cotton',
    sa.Column('cotton_id', sa.Integer(), nullable=False),
    sa.Column('origin_country', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('staple_length', sa.String(length=30), nullable=True),
    sa.Column('spot_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ice_futures_near', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ice_futures_3m', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ice_futures_6m', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ice_futures_9m', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ice_futures_12m', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('contango_signal', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('wasde_forecast', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('wasde_ending_stocks', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('wasde_su_ratio_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('crop_year', sa.Integer(), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('refresh', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('cotton_id')
    )
    op.create_table('crude_oil',
    sa.Column('crude_oil_id', sa.Integer(), nullable=False),
    sa.Column('brent_spot', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('wti_spot', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('trend_30d_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('days_since_refresh', sa.Integer(), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('refresh', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('crude_oil_id')
    )
    op.create_table('current_landed_cost_per_dozen',
    sa.Column('output_id', sa.Integer(), nullable=False),
    sa.Column('spec_id', sa.Integer(), nullable=True),
    sa.Column('corridor', sa.String(length=100), nullable=True),
    sa.Column('landed_cost_doz', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('fob_component', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('freight_component', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('duty_component', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('insurance_component', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('market_benchmark_doz', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('variance_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('data_quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('output_id')
    )
    op.create_table('customs_broker_partner',
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('partner_name', sa.String(length=255), nullable=True),
    sa.Column('api_base_url', sa.String(length=255), nullable=True),
    sa.Column('license_number', sa.String(length=255), nullable=True),
    sa.Column('files_with_cbp', sa.Boolean(), nullable=True),
    sa.Column('revenue_model', sa.String(length=255), nullable=True),
    sa.Column('fee_per_clearance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('partner_id')
    )
    op.create_table('customs_clearance_filing',
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('hs_code_id', sa.Integer(), nullable=True),
    sa.Column('importer_of_record', sa.String(length=255), nullable=True),
    sa.Column('declared_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quantity_units', sa.Integer(), nullable=True),
    sa.Column('country_of_origin', sa.String(length=100), nullable=True),
    sa.Column('vessel_name', sa.String(length=255), nullable=True),
    sa.Column('bol_number', sa.String(length=255), nullable=True),
    sa.Column('entry_number', sa.String(length=255), nullable=True),
    sa.Column('duty_amount_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('clearance_date', sa.Date(), nullable=True),
    sa.Column('cbp_response_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('filing_id')
    )
    op.create_table('data_licensing_revenue',
    sa.Column('revenue_id', sa.Integer(), nullable=False),
    sa.Column('annual_fee_range', sa.String(length=50), nullable=True),
    sa.Column('customer_types', sa.String(length=255), nullable=True),
    sa.Column('data_products', sa.String(length=255), nullable=True),
    sa.Column('exclusivity_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('revenue_id')
    )
    op.create_table('de_minimis',
    sa.Column('de_minimis_id', sa.Integer(), nullable=False),
    sa.Column('threshold_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('duty_free_entry', sa.String(length=50), nullable=True),
    sa.Column('regulatory_pressure_flag', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('de_minimis_id')
    )
    op.create_table('demand_signals',
    sa.Column('demand_signal_id', sa.Integer(), nullable=False),
    sa.Column('retailer_id', sa.Integer(), nullable=True),
    sa.Column('store_expansion', sa.String(length=255), nullable=True),
    sa.Column('inventory_improving', sa.String(length=255), nullable=True),
    sa.Column('margin_compression', sa.String(length=255), nullable=True),
    sa.Column('buying_volume_signal', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('demand_signal_id')
    )
    op.create_table('duty_drawback',
    sa.Column('drawback_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('eligibility_flag', sa.Boolean(), nullable=True),
    sa.Column('estimated_recovery', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('drawback_type', sa.String(length=255), nullable=True),
    sa.Column('specialist_referred', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('drawback_id')
    )
    op.create_table('dyeing_units',
    sa.Column('dyeing_unit_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('capacity_tons_month', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('chemical_cost_structure', sa.String(length=255), nullable=True),
    sa.Column('energy_intensity', sa.String(length=100), nullable=True),
    sa.Column('crude_sensitivity_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('dyeing_unit_id')
    )
    op.create_table('energy_cost',
    sa.Column('energy_cost_id', sa.Integer(), nullable=False),
    sa.Column('india_kwh_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('bangladesh_kwh_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('vietnam_kwh_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('china_kwh_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('turkey_kwh_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('morocco_kwh_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cambodia_kwh_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pakistan_kwh_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('update_frequency', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('energy_cost_id')
    )
    op.create_table('eu_csddd',
    sa.Column('csddd_id', sa.Integer(), nullable=False),
    sa.Column('supply_chain_mapping_required', sa.String(length=255), nullable=True),
    sa.Column('verification_requirement', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('csddd_id')
    )
    op.create_table('factory_capacity_constraints',
    sa.Column('output_id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=True),
    sa.Column('corridor', sa.String(length=100), nullable=True),
    sa.Column('constraint_type', sa.String(length=255), nullable=True),
    sa.Column('severity_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('lead_time_change_wks', sa.Integer(), nullable=True),
    sa.Column('affected_product_types', sa.String(length=255), nullable=True),
    sa.Column('implication', sa.String(length=255), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('output_id')
    )
    op.create_table('factory_financing_cost',
    sa.Column('financing_cost_id', sa.Integer(), nullable=False),
    sa.Column('india_rate_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('bangladesh_rate_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('vietnam_rate_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('china_rate_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('turkey_rate_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('morocco_rate_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cambodia_rate_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pakistan_rate_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('refresh', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('financing_cost_id')
    )
    op.create_table('factory_financing_impact',
    sa.Column('output_id', sa.Integer(), nullable=False),
    sa.Column('country_a', sa.String(length=100), nullable=True),
    sa.Column('country_b', sa.String(length=100), nullable=True),
    sa.Column('rate_a_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rate_b_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rate_diff_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('impact_per_dozen_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('annualised_impact_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('implication', sa.String(length=255), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('output_id')
    )
    op.create_table('fob_price_calculation',
    sa.Column('fob_calc_id', sa.Integer(), nullable=False),
    sa.Column('spec_id', sa.Integer(), nullable=True),
    sa.Column('corridor', sa.String(length=100), nullable=True),
    sa.Column('fabric_cost_doz', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cmt_cost_doz', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('trim_cost_doz', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('overhead_doz', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('financing_cost_doz', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('fob_price_doz', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('fob_calc_id')
    )
    op.create_table('forward_landed_cost_90day',
    sa.Column('output_id', sa.Integer(), nullable=False),
    sa.Column('spec_id', sa.Integer(), nullable=True),
    sa.Column('corridor', sa.String(length=100), nullable=True),
    sa.Column('p10', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('p50', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('p90', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('dominant_risk_factor', sa.String(length=255), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('output_id')
    )
    op.create_table('free_trade_agreements',
    sa.Column('fta_id', sa.Integer(), nullable=False),
    sa.Column('agreement_name', sa.String(length=255), nullable=True),
    sa.Column('beneficiary_countries', sa.String(length=255), nullable=True),
    sa.Column('duty_reduction_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('yarn_forward_rule', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('fta_id')
    )
    op.create_table('freight_booking_window',
    sa.Column('output_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('recommended_book_by', sa.Date(), nullable=True),
    sa.Column('current_rate_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate_trend', sa.String(length=50), nullable=True),
    sa.Column('urgency', sa.String(length=50), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('output_id')
    )
    op.create_table('fx_rates',
    sa.Column('fx_rate_id', sa.Integer(), nullable=False),
    sa.Column('usd_inr', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('usd_bdt', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('usd_vnd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('usd_cny', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('usd_try', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('usd_mad', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('usd_pkr', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('refresh', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('fx_rate_id')
    )
    op.create_table('hedge_opportunity',
    sa.Column('hedge_opportunity_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('commodity', sa.String(length=50), nullable=True),
    sa.Column('tenor_months', sa.Integer(), nullable=True),
    sa.Column('recommended_quantity', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('spot_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('futures_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('basis', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('potential_saving_doz', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('risk_if_unhedged_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('recommended_action', sa.String(length=255), nullable=True),
    sa.Column('pillar_quote_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('hedge_opportunity_id')
    )
    op.create_table('hedge_opportunity_recommendation',
    sa.Column('output_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('commodity', sa.String(length=50), nullable=True),
    sa.Column('tenor_months', sa.Integer(), nullable=True),
    sa.Column('recommended_action', sa.String(length=255), nullable=True),
    sa.Column('potential_saving_doz', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('risk_if_unhedged', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('output_id')
    )
    op.create_table('hedge_portfolio',
    sa.Column('hedge_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('hedged_commodity', sa.String(length=50), nullable=True),
    sa.Column('strike_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('quantity_bales', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('notional_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('premium_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('execution_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('current_mtm_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unrealised_pnl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pillar_hedge_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('hedge_id')
    )
    op.create_table('hs_codes',
    sa.Column('hs_code_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('hs_code_id')
    )
    op.create_table('importer',
    sa.Column('importer_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('annual_revenue_usd', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('primary_corridors', sa.String(length=255), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), nullable=True),
    sa.Column('subscription_fee_monthly', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('subscribes_to_intelligence', sa.Boolean(), nullable=True),
    sa.Column('executes_hedges', sa.Boolean(), nullable=True),
    sa.Column('books_freight', sa.Boolean(), nullable=True),
    sa.Column('manages_programs', sa.Boolean(), nullable=True),
    sa.Column('discovers_factories', sa.Boolean(), nullable=True),
    sa.Column('account_manager', sa.String(length=255), nullable=True),
    sa.Column('joined_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('importer_id')
    )
    op.create_table('importer_working_capital',
    sa.Column('working_capital_id', sa.Integer(), nullable=False),
    sa.Column('importer_id', sa.Integer(), nullable=True),
    sa.Column('annual_borrowing_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('typical_inventory_days', sa.Integer(), nullable=True),
    sa.Column('cost_of_carry_per_dozen', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('working_capital_id')
    )
    op.create_table('intelligence_subscription',
    sa.Column('revenue_id', sa.Integer(), nullable=False),
    sa.Column('importer_id', sa.Integer(), nullable=True),
    sa.Column('monthly_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('billing_cycle', sa.String(length=50), nullable=True),
    sa.Column('target_gross_margin_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('revenue_id')
    )
    op.create_table('intermodal_rail_rfq',
    sa.Column('rail_rfq_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('origin_port', sa.String(length=255), nullable=True),
    sa.Column('destination_dc', sa.String(length=255), nullable=True),
    sa.Column('distance_miles', sa.Integer(), nullable=True),
    sa.Column('container_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('awarded_carrier_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('rail_rfq_id')
    )
    op.create_table('knit_fabric',
    sa.Column('fabric_id', sa.Integer(), nullable=False),
    sa.Column('construction', sa.String(length=100), nullable=True),
    sa.Column('weight_gsm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fibre_content', sa.String(length=255), nullable=True),
    sa.Column('finish', sa.String(length=100), nullable=True),
    sa.Column('origin_country', sa.String(length=100), nullable=True),
    sa.Column('price_per_kg', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('fabric_id')
    )
    op.create_table('knitting_mills',
    sa.Column('knitting_mill_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('capacity_tons_month', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('utilisation_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('machine_types', sa.String(length=255), nullable=True),
    sa.Column('certifications', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('knitting_mill_id')
    )
    op.create_table('labour_cost_by_country',
    sa.Column('labour_cost_id', sa.Integer(), nullable=False),
    sa.Column('india_tirupur', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('india_coimbatore', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('india_bangalore', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('bangladesh_dhaka', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('bangladesh_gazipur', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('bangladesh_chittagong', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('vietnam_hcmc', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('vietnam_hanoi', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('china_guangdong', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('china_zhejiang', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('turkey_istanbul', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('morocco_casablanca', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cambodia_national', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pakistan_national', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('refresh', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('labour_cost_id')
    )
    op.create_table('local_inland_freight',
    sa.Column('inland_freight_id', sa.Integer(), nullable=False),
    sa.Column('factory_to_port_cost_country', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('inland_freight_id')
    )
    op.create_table('major_retailers',
    sa.Column('retailer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('store_count', sa.Integer(), nullable=True),
    sa.Column('total_sales', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('apparel_revenue', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gross_margin', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('inventory_turnover', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('forward_guidance', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('retailer_id')
    )
    op.create_table('manufacturer',
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('primary_product_type', sa.String(length=255), nullable=True),
    sa.Column('annual_export_usd', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('primary_importer_markets', sa.String(length=255), nullable=True),
    sa.Column('platform_tier', sa.String(length=50), nullable=True),
    sa.Column('manages_programs', sa.Boolean(), nullable=True),
    sa.Column('receives_pos', sa.Boolean(), nullable=True),
    sa.Column('submits_milestones', sa.Boolean(), nullable=True),
    sa.Column('accesses_scf', sa.Boolean(), nullable=True),
    sa.Column('builds_profile', sa.Boolean(), nullable=True),
    sa.Column('joined_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('manufacturer_id')
    )
    op.create_table('manufacturer_profile',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('trade_name', sa.String(length=255), nullable=True),
    sa.Column('factory_type', sa.String(length=50), nullable=True),
    sa.Column('utilisation_pct_live', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('otd_rate_verified', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('platform_tier', sa.String(length=50), nullable=True),
    sa.Column('profile_visibility', sa.String(length=50), nullable=True),
    sa.Column('supply_chain_finance_eligible', sa.Boolean(), nullable=True),
    sa.Column('contact_primary', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('most_cost_effective_corridor',
    sa.Column('output_id', sa.Integer(), nullable=False),
    sa.Column('spec_id', sa.Integer(), nullable=True),
    sa.Column('best_corridor', sa.String(length=100), nullable=True),
    sa.Column('cost_differential_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('second_best_corridor', sa.String(length=100), nullable=True),
    sa.Column('key_driver', sa.String(length=255), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('output_id')
    )
    op.create_table('ocean_freight_rates',
    sa.Column('ocean_rate_id', sa.Integer(), nullable=False),
    sa.Column('chittagong_la_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('chennai_la_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('hcmc_la_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('shanghai_la_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rate_per_40ft_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('transit_days', sa.Integer(), nullable=True),
    sa.Column('port_congestion_index', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('ocean_rate_id')
    )
    op.create_table('ocean_freight_rfq',
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('origin_port', sa.String(length=255), nullable=True),
    sa.Column('destination_port', sa.String(length=255), nullable=True),
    sa.Column('cargo_spec', sa.String(length=255), nullable=True),
    sa.Column('container_size', sa.String(length=50), nullable=True),
    sa.Column('ready_to_ship_date', sa.Date(), nullable=True),
    sa.Column('hs_code_id', sa.Integer(), nullable=True),
    sa.Column('estimated_weight_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bid_deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('awarded_carrier_id', sa.Integer(), nullable=True),
    sa.Column('awarded_rate_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('award_timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('rfq_id')
    )
    op.create_table('origin_drayage_rfq',
    sa.Column('origin_drayage_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('factory_location', sa.String(length=255), nullable=True),
    sa.Column('origin_port', sa.String(length=255), nullable=True),
    sa.Column('ready_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('awarded_carrier_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('origin_drayage_id')
    )
    op.create_table('otd_risk_score_per_program',
    sa.Column('output_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sector_utilisation', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('red_sea_transit_add', sa.Integer(), nullable=True),
    sa.Column('cmt_days_remaining', sa.Integer(), nullable=True),
    sa.Column('risk_factors', sa.String(length=255), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('output_id')
    )
    op.create_table('pillar_hq_partner',
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('partner_name', sa.String(length=255), nullable=True),
    sa.Column('integration_type', sa.String(length=255), nullable=True),
    sa.Column('api_base_url', sa.String(length=255), nullable=True),
    sa.Column('commodities_covered', sa.String(length=255), nullable=True),
    sa.Column('revenue_share_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('contract_signed_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('partner_id')
    )
    op.create_table('polyester_pet_chips',
    sa.Column('chip_id', sa.Integer(), nullable=False),
    sa.Column('chinese_spot', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('asian_spot', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('polyester_yarn_price_lag', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('chip_id')
    )
    op.create_table('prediction_log',
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('spec_id', sa.Integer(), nullable=True),
    sa.Column('prediction_type', sa.String(length=100), nullable=True),
    sa.Column('corridor', sa.String(length=100), nullable=True),
    sa.Column('predicted_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('p10', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('p50', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('p90', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('prediction_timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('actual_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('accuracy_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('data_snapshot_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_table('product_specification',
    sa.Column('spec_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('hs_code_id', sa.Integer(), nullable=True),
    sa.Column('fibre_content', sa.String(length=255), nullable=True),
    sa.Column('construction', sa.String(length=255), nullable=True),
    sa.Column('weight_gsm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('typical_fob_low', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('typical_fob_high', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('prototype_corridor_1', sa.String(length=100), nullable=True),
    sa.Column('prototype_corridor_2', sa.String(length=100), nullable=True),
    sa.Column('prototype_corridor_3', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('spec_id')
    )
    op.create_table('program',
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('importer_id', sa.Integer(), nullable=True),
    sa.Column('factory_id', sa.Integer(), nullable=True),
    sa.Column('spec_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('quantity_units', sa.Integer(), nullable=True),
    sa.Column('fob_price_agreed', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('delivery_date_committed', sa.Date(), nullable=True),
    sa.Column('origin_port', sa.String(length=255), nullable=True),
    sa.Column('destination_port', sa.String(length=255), nullable=True),
    sa.Column('destination_dc', sa.String(length=255), nullable=True),
    sa.Column('cmt_start_date', sa.Date(), nullable=True),
    sa.Column('fabric_cut_date', sa.Date(), nullable=True),
    sa.Column('ship_date_planned', sa.Date(), nullable=True),
    sa.Column('ship_date_actual', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('commodity_hedge_status', sa.String(length=50), nullable=True),
    sa.Column('hedge_id', sa.Integer(), nullable=True),
    sa.Column('freight_booking_id', sa.Integer(), nullable=True),
    sa.Column('customs_clearance_id', sa.Integer(), nullable=True),
    sa.Column('otd_risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('landed_cost_estimated', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('landed_cost_actual', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('program_id')
    )
    op.create_table('program_pnl_with_levers',
    sa.Column('output_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('landed_cost_current', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('retail_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('margin_current_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('hedge_saving_available', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('scf_saving_available', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('freight_saving_available', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('corridor_shift_saving', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('margin_with_all_levers_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('priority_lever', sa.String(length=255), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('output_id')
    )
    op.create_table('pta',
    sa.Column('pta_id', sa.Integer(), nullable=False),
    sa.Column('chinese_spot', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('asian_export', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('polyester_chip_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('pta_id')
    )
    op.create_table('px_paraxylene',
    sa.Column('px_id', sa.Integer(), nullable=False),
    sa.Column('asian_spot_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pta_price_lag_1_2w', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('px_id')
    )
    op.create_table('red_sea_disruption',
    sa.Column('disruption_id', sa.Integer(), nullable=False),
    sa.Column('disruption_name', sa.String(length=255), nullable=True),
    sa.Column('affected_routes', sa.String(length=255), nullable=True),
    sa.Column('severity_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('extra_transit_days', sa.Integer(), nullable=True),
    sa.Column('extra_cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('date_resolved', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('disruption_id')
    )
    op.create_table('retailer_demand_forecast',
    sa.Column('output_id', sa.Integer(), nullable=False),
    sa.Column('retailer_id', sa.Integer(), nullable=True),
    sa.Column('buying_volume_signal', sa.String(length=255), nullable=True),
    sa.Column('store_count_trend', sa.String(length=255), nullable=True),
    sa.Column('unit_growth_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('category_focus', sa.String(length=255), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('output_id')
    )
    op.create_table('revenue_transaction',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('revenue_type', sa.String(length=100), nullable=True),
    sa.Column('partner_name', sa.String(length=255), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_to_artemis', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('scf_opportunity_per_factory',
    sa.Column('output_id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('current_financing_rate_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('scf_rate_offered_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('saving_per_dozen', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_saving_program', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('eligible', sa.Boolean(), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('output_id')
    )
    op.create_table('scf_provider_partner',
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('partner_name', sa.String(length=255), nullable=True),
    sa.Column('api_base_url', sa.String(length=255), nullable=True),
    sa.Column('funds_factories', sa.Boolean(), nullable=True),
    sa.Column('max_advance_rate_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('min_invoice_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('revenue_share_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('partner_id')
    )
    op.create_table('seasonal_patterns',
    sa.Column('seasonal_pattern_id', sa.Integer(), nullable=False),
    sa.Column('ss_factory_commit_window', sa.String(length=50), nullable=True),
    sa.Column('ss_delivery_window', sa.String(length=50), nullable=True),
    sa.Column('fw_factory_commit_window', sa.String(length=50), nullable=True),
    sa.Column('fw_delivery_window', sa.String(length=50), nullable=True),
    sa.Column('freight_book_lead_days', sa.Integer(), nullable=True),
    sa.Column('hedge_window_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('seasonal_pattern_id')
    )
    op.create_table('shipper',
    sa.Column('shipper_id', sa.Integer(), nullable=False),
    sa.Column('factory_name', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('hs_codes_shipped', sa.String(length=255), nullable=True),
    sa.Column('volume_by_month', sa.String(length=255), nullable=True),
    sa.Column('active_buyers', sa.String(length=255), nullable=True),
    sa.Column('yoy_trend', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('shipper_id')
    )
    op.create_table('spinning_mills',
    sa.Column('spinning_mill_id', sa.Integer(), nullable=False),
    sa.Column('location_country', sa.String(length=100), nullable=True),
    sa.Column('location_city', sa.String(length=100), nullable=True),
    sa.Column('capacity_tons_month', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('utilisation_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('certifications', sa.String(length=255), nullable=True),
    sa.Column('lead_time_weeks', sa.Integer(), nullable=True),
    sa.Column('financing_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('spinning_mill_id')
    )
    op.create_table('supply_chain_finance_offer',
    sa.Column('scf_offer_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('factory_id', sa.Integer(), nullable=True),
    sa.Column('invoice_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('advance_rate_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discount_rate_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('effective_rate_saving', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('offer_date', sa.Date(), nullable=True),
    sa.Column('acceptance_date', sa.Date(), nullable=True),
    sa.Column('disbursement_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('scf_provider', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('scf_offer_id')
    )
    op.create_table('tariff_exposure_analysis',
    sa.Column('output_id', sa.Integer(), nullable=False),
    sa.Column('spec_id', sa.Integer(), nullable=True),
    sa.Column('current_corridor', sa.String(length=100), nullable=True),
    sa.Column('current_duty_rate_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('alt_corridor_1', sa.String(length=100), nullable=True),
    sa.Column('duty_rate_alt_1_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('saving_pct_alt_1', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('alt_corridor_2', sa.String(length=100), nullable=True),
    sa.Column('duty_rate_alt_2_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('saving_pct_alt_2', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('output_id')
    )
    op.create_table('top5_competitor_sourcing',
    sa.Column('output_id', sa.Integer(), nullable=False),
    sa.Column('importer_name', sa.String(length=255), nullable=True),
    sa.Column('from_corridor', sa.String(length=100), nullable=True),
    sa.Column('to_corridor', sa.String(length=100), nullable=True),
    sa.Column('volume_shift_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('date_detected', sa.Date(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('signal_source', sa.String(length=255), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('output_id')
    )
    op.create_table('trade_flow_signals',
    sa.Column('trade_signal_id', sa.Integer(), nullable=False),
    sa.Column('market_share_by_origin', sa.String(length=255), nullable=True),
    sa.Column('competitor_shifts', sa.String(length=255), nullable=True),
    sa.Column('new_entrants', sa.String(length=255), nullable=True),
    sa.Column('seasonal_patterns', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('trade_signal_id')
    )
    op.create_table('trim_cost',
    sa.Column('trim_id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(length=255), nullable=True),
    sa.Column('labels_per_doz', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('buttons_zippers_doz', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('polybag_packaging_doz', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_trim_cost_doz', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('trim_id')
    )
    op.create_table('uflpa',
    sa.Column('uflpa_id', sa.Integer(), nullable=False),
    sa.Column('rebuttable_presumption', sa.String(length=255), nullable=True),
    sa.Column('border_block_risk', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('xinjiang_inputs', sa.String(length=255), nullable=True),
    sa.Column('compliance_doc_cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('uflpa_id')
    )
    op.create_table('us_drayage_rfq',
    sa.Column('drayage_rfq_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('origin_port', sa.String(length=255), nullable=True),
    sa.Column('destination_dc', sa.String(length=255), nullable=True),
    sa.Column('container_type', sa.String(length=50), nullable=True),
    sa.Column('pickup_date', sa.Date(), nullable=True),
    sa.Column('delivery_deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('awarded_carrier_id', sa.Integer(), nullable=True),
    sa.Column('awarded_rate_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('drayage_rfq_id')
    )
    op.create_table('us_duty_rates',
    sa.Column('duty_rate_id', sa.Integer(), nullable=False),
    sa.Column('hs_code_id', sa.Integer(), nullable=True),
    sa.Column('ntr_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('section_301_china', sa.String(length=50), nullable=True),
    sa.Column('gsp_status', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('duty_rate_id')
    )
    op.create_table('viscose_rayon',
    sa.Column('viscose_id', sa.Integer(), nullable=False),
    sa.Column('asian_spot_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('blended_yarn_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('viscose_id')
    )
    op.create_table('yarn',
    sa.Column('yarn_id', sa.Integer(), nullable=False),
    sa.Column('fibre_type', sa.String(length=100), nullable=True),
    sa.Column('count', sa.String(length=50), nullable=True),
    sa.Column('spinning_method', sa.String(length=100), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('origin_city', sa.String(length=100), nullable=True),
    sa.Column('price_per_kg', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('availability_signal', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('yarn_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yarn')
    op.drop_table('viscose_rayon')
    op.drop_table('us_duty_rates')
    op.drop_table('us_drayage_rfq')
    op.drop_table('uflpa')
    op.drop_table('trim_cost')
    op.drop_table('trade_flow_signals')
    op.drop_table('top5_competitor_sourcing')
    op.drop_table('tariff_exposure_analysis')
    op.drop_table('supply_chain_finance_offer')
    op.drop_table('spinning_mills')
    op.drop_table('shipper')
    op.drop_table('seasonal_patterns')
    op.drop_table('scf_provider_partner')
    op.drop_table('scf_opportunity_per_factory')
    op.drop_table('revenue_transaction')
    op.drop_table('retailer_demand_forecast')
    op.drop_table('red_sea_disruption')
    op.drop_table('px_paraxylene')
    op.drop_table('pta')
    op.drop_table('program_pnl_with_levers')
    op.drop_table('program')
    op.drop_table('product_specification')
    op.drop_table('prediction_log')
    op.drop_table('polyester_pet_chips')
    op.drop_table('pillar_hq_partner')
    op.drop_table('otd_risk_score_per_program')
    op.drop_table('origin_drayage_rfq')
    op.drop_table('ocean_freight_rfq')
    op.drop_table('ocean_freight_rates')
    op.drop_table('most_cost_effective_corridor')
    op.drop_table('manufacturer_profile')
    op.drop_table('manufacturer')
    op.drop_table('major_retailers')
    op.drop_table('local_inland_freight')
    op.drop_table('labour_cost_by_country')
    op.drop_table('knitting_mills')
    op.drop_table('knit_fabric')
    op.drop_table('intermodal_rail_rfq')
    op.drop_table('intelligence_subscription')
    op.drop_table('importer_working_capital')
    op.drop_table('importer')
    op.drop_table('hs_codes')
    op.drop_table('hedge_portfolio')
    op.drop_table('hedge_opportunity_recommendation')
    op.drop_table('hedge_opportunity')
    op.drop_table('fx_rates')
    op.drop_table('freight_booking_window')
    op.drop_table('free_trade_agreements')
    op.drop_table('forward_landed_cost_90day')
    op.drop_table('fob_price_calculation')
    op.drop_table('factory_financing_impact')
    op.drop_table('factory_financing_cost')
    op.drop_table('factory_capacity_constraints')
    op.drop_table('eu_csddd')
    op.drop_table('energy_cost')
    op.drop_table('dyeing_units')
    op.drop_table('duty_drawback')
    op.drop_table('demand_signals')
    op.drop_table('de_minimis')
    op.drop_table('data_licensing_revenue')
    op.drop_table('customs_clearance_filing')
    op.drop_table('customs_broker_partner')
    op.drop_table('current_landed_cost_per_dozen')
    op.drop_table('crude_oil')
    op.drop_table('cotton')
    op.drop_table('consignee')
    op.drop_table('competitor_factory_intel')
    op.drop_table('commodity_risk_in_open_programs')
    op.drop_table('commodity_futures')
    op.drop_table('cmt_factories')
    op.drop_table('carrier_network')
    op.drop_table('carrier_bid')
    op.drop_table('carrier')
    op.drop_table('air_freight')
    # ### end Alembic commands ###
