"""add_updated_at_to_carrier_bid

Revision ID: 5bc90f28931e
Revises: 0f5b3ec355dd
Create Date: 2026-06-07 10:40:13.330507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bc90f28931e'
down_revision: Union[str, Sequence[str], None] = '0f5b3ec355dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
