"""add_retailer_signal_evidence_and_corroboration_fields

Revision ID: 60079f70e06a
Revises: 063deaba26fb
Create Date: 2026-06-08 00:14:19.973002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60079f70e06a'
down_revision: Union[str, Sequence[str], None] = '063deaba26fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retailer_signal_evidence',
    sa.Column('evidence_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extract_id', sa.Integer(), nullable=True),
    sa.Column('retailer_id', sa.Integer(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('document_section', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('speaker', sa.String(length=20), nullable=True),
    sa.Column('raw_text_passage', sa.Text(), nullable=True),
    sa.Column('is_forward_looking', sa.Boolean(), nullable=True),
    sa.Column('contains_number', sa.Boolean(), nullable=True),
    sa.Column('number_mentioned', sa.String(length=50), nullable=True),
    sa.Column('time_period_referenced', sa.String(length=30), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('document_priority', sa.Integer(), nullable=True),
    sa.Column('corroborates_master', sa.Boolean(), nullable=True),
    sa.Column('contradicts_master', sa.Boolean(), nullable=True),
    sa.Column('is_analyst_pressure', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    with op.batch_alter_table('retailer_intelligence_extract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evidence_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('corroboration_score', sa.Numeric(precision=4, scale=2), nullable=True))
        batch_op.add_column(sa.Column('has_contradiction', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('primary_document_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('primary_speaker', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retailer_intelligence_extract', schema=None) as batch_op:
        batch_op.drop_column('primary_speaker')
        batch_op.drop_column('primary_document_type')
        batch_op.drop_column('has_contradiction')
        batch_op.drop_column('corroboration_score')
        batch_op.drop_column('evidence_count')

    op.drop_table('retailer_signal_evidence')
    # ### end Alembic commands ###
