"""walmart_entity_separation_inventory_consumption_fields

Revision ID: c6f6e9e7753e
Revises: 60079f70e06a
Create Date: 2026-06-08 12:06:50.786597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f6e9e7753e'
down_revision: Union[str, Sequence[str], None] = '60079f70e06a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retailer_financials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_8k_presentation_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('walmart_us_general_merch_usd', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('walmart_us_general_merch_pct', sa.Numeric(precision=6, scale=4), nullable=True))
        batch_op.add_column(sa.Column('walmart_us_general_merch_yoy_pct', sa.Numeric(precision=8, scale=4), nullable=True))
        batch_op.add_column(sa.Column('walmart_us_ecommerce_usd', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('walmart_us_ecommerce_pct_of_total', sa.Numeric(precision=6, scale=4), nullable=True))
        batch_op.add_column(sa.Column('walmart_us_ecommerce_yoy_growth_pct', sa.Numeric(precision=8, scale=4), nullable=True))
        batch_op.add_column(sa.Column('sams_club_home_apparel_usd', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('sams_club_home_apparel_pct', sa.Numeric(precision=6, scale=4), nullable=True))
        batch_op.add_column(sa.Column('sams_club_home_apparel_yoy_pct', sa.Numeric(precision=8, scale=4), nullable=True))
        batch_op.add_column(sa.Column('sams_club_total_usd', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('sams_club_ecommerce_usd', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('sams_club_comp_sales_ex_fuel_pct', sa.Numeric(precision=8, scale=4), nullable=True))
        batch_op.add_column(sa.Column('walmart_us_store_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sams_club_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('walmart_us_model_note', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('sams_club_model_note', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('walmart_us_inventory_usd', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('sams_club_inventory_usd', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('walmart_international_inventory_usd', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('walmart_us_inventory_yoy_change_pct', sa.Numeric(precision=8, scale=4), nullable=True))
        batch_op.add_column(sa.Column('sams_club_inventory_yoy_change_pct', sa.Numeric(precision=8, scale=4), nullable=True))
        batch_op.add_column(sa.Column('walmart_us_inventory_days', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('sams_club_inventory_days', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('walmart_us_inventory_to_sales_ratio', sa.Numeric(precision=8, scale=4), nullable=True))
        batch_op.add_column(sa.Column('general_merch_inventory_proxy_signal', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('inventory_positioning_language', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('inventory_change_narrative', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('transaction_count_growth_pct', sa.Numeric(precision=8, scale=4), nullable=True))
        batch_op.add_column(sa.Column('average_transaction_value_change_pct', sa.Numeric(precision=8, scale=4), nullable=True))
        batch_op.add_column(sa.Column('ticket_vs_traffic_split', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('walmart_plus_member_count', sa.Numeric(precision=10, scale=0), nullable=True))
        batch_op.add_column(sa.Column('walmart_plus_membership_growth_pct', sa.Numeric(precision=8, scale=4), nullable=True))
        batch_op.add_column(sa.Column('sams_club_member_count', sa.Numeric(precision=10, scale=0), nullable=True))
        batch_op.add_column(sa.Column('sams_club_membership_fee_revenue_usd', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('sams_club_member_count_yoy_pct', sa.Numeric(precision=8, scale=4), nullable=True))
        batch_op.add_column(sa.Column('private_brand_mix_change_bps', sa.Numeric(precision=8, scale=2), nullable=True))

    with op.batch_alter_table('retailer_signal_evidence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_is_sec_filing', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retailer_signal_evidence', schema=None) as batch_op:
        batch_op.drop_column('source_is_sec_filing')

    with op.batch_alter_table('retailer_financials', schema=None) as batch_op:
        batch_op.drop_column('private_brand_mix_change_bps')
        batch_op.drop_column('sams_club_member_count_yoy_pct')
        batch_op.drop_column('sams_club_membership_fee_revenue_usd')
        batch_op.drop_column('sams_club_member_count')
        batch_op.drop_column('walmart_plus_membership_growth_pct')
        batch_op.drop_column('walmart_plus_member_count')
        batch_op.drop_column('ticket_vs_traffic_split')
        batch_op.drop_column('average_transaction_value_change_pct')
        batch_op.drop_column('transaction_count_growth_pct')
        batch_op.drop_column('inventory_change_narrative')
        batch_op.drop_column('inventory_positioning_language')
        batch_op.drop_column('general_merch_inventory_proxy_signal')
        batch_op.drop_column('walmart_us_inventory_to_sales_ratio')
        batch_op.drop_column('sams_club_inventory_days')
        batch_op.drop_column('walmart_us_inventory_days')
        batch_op.drop_column('sams_club_inventory_yoy_change_pct')
        batch_op.drop_column('walmart_us_inventory_yoy_change_pct')
        batch_op.drop_column('walmart_international_inventory_usd')
        batch_op.drop_column('sams_club_inventory_usd')
        batch_op.drop_column('walmart_us_inventory_usd')
        batch_op.drop_column('sams_club_model_note')
        batch_op.drop_column('walmart_us_model_note')
        batch_op.drop_column('sams_club_count')
        batch_op.drop_column('walmart_us_store_count')
        batch_op.drop_column('sams_club_comp_sales_ex_fuel_pct')
        batch_op.drop_column('sams_club_ecommerce_usd')
        batch_op.drop_column('sams_club_total_usd')
        batch_op.drop_column('sams_club_home_apparel_yoy_pct')
        batch_op.drop_column('sams_club_home_apparel_pct')
        batch_op.drop_column('sams_club_home_apparel_usd')
        batch_op.drop_column('walmart_us_ecommerce_yoy_growth_pct')
        batch_op.drop_column('walmart_us_ecommerce_pct_of_total')
        batch_op.drop_column('walmart_us_ecommerce_usd')
        batch_op.drop_column('walmart_us_general_merch_yoy_pct')
        batch_op.drop_column('walmart_us_general_merch_pct')
        batch_op.drop_column('walmart_us_general_merch_usd')
        batch_op.drop_column('source_8k_presentation_url')

    # ### end Alembic commands ###
