"""add_reference_seed_tables

Revision ID: caab5ea51fcf
Revises: 353dd690a9d9
Create Date: 2026-06-09 12:31:02.737159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caab5ea51fcf'
down_revision: Union[str, Sequence[str], None] = '353dd690a9d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geopolitical_risk_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('affected_region', sa.String(), nullable=False),
    sa.Column('affected_corridors', sa.String(), nullable=False),
    sa.Column('freight_impact_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('lead_time_impact_days', sa.Integer(), nullable=False),
    sa.Column('production_disruption_risk', sa.String(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expected_resolution_date', sa.Date(), nullable=True),
    sa.Column('actual_resolution_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('analyst_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('geopolitical_risk_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geopolitical_risk_event_as_of_date'), ['as_of_date'], unique=False)

    op.create_table('government_export_incentive',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('program_name', sa.String(), nullable=False),
    sa.Column('program_type', sa.String(), nullable=False),
    sa.Column('applicable_hs_codes', sa.String(), nullable=False),
    sa.Column('benefit_rate_pct_fob', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('benefit_per_dozen_usd_estimate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('benefit_recipient', sa.String(), nullable=False),
    sa.Column('eligibility_criteria', sa.String(), nullable=True),
    sa.Column('processing_time_days', sa.Integer(), nullable=True),
    sa.Column('annual_cap_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('last_verified', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('government_export_incentive', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_government_export_incentive_effective_date'), ['effective_date'], unique=False)

    op.create_table('marine_insurance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('corridor', sa.String(), nullable=False),
    sa.Column('all_risk_rate_pct_cif', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('war_risk_rate_pct_cif', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_effective_rate_pct_cif', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('route_risk_level', sa.String(), nullable=False),
    sa.Column('active_war_risk_surcharge', sa.Boolean(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marine_insurance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marine_insurance_as_of_date'), ['as_of_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_marine_insurance_corridor'), ['corridor'], unique=False)

    op.create_table('us_import_duty_rate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ntr_rate_6109_10_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('ntr_rate_6110_20_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('ntr_rate_6109_90_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('ntr_rate_6111_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('section_301_china_6109_10_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('section_301_china_6110_20_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('section_301_china_6109_90_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('gsp_status_by_country', sa.String(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('us_import_duty_rate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_us_import_duty_rate_effective_date'), ['effective_date'], unique=False)

    op.create_table('shipping_lane_risk',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lane_name', sa.String(), nullable=False),
    sa.Column('corridors_affected', sa.String(), nullable=False),
    sa.Column('current_risk_level', sa.String(), nullable=False),
    sa.Column('is_currently_disrupted', sa.Boolean(), nullable=False),
    sa.Column('alternative_route', sa.String(), nullable=True),
    sa.Column('additional_transit_days', sa.Integer(), nullable=True),
    sa.Column('additional_cost_per_40ft_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('current_event_id', sa.Integer(), nullable=True),
    sa.Column('disruption_since', sa.Date(), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_event_id'], ['geopolitical_risk_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipping_lane_risk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipping_lane_risk_as_of_date'), ['as_of_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipping_lane_risk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipping_lane_risk_as_of_date'))

    op.drop_table('shipping_lane_risk')
    with op.batch_alter_table('us_import_duty_rate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_us_import_duty_rate_effective_date'))

    op.drop_table('us_import_duty_rate')
    with op.batch_alter_table('marine_insurance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marine_insurance_corridor'))
        batch_op.drop_index(batch_op.f('ix_marine_insurance_as_of_date'))

    op.drop_table('marine_insurance')
    with op.batch_alter_table('government_export_incentive', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_government_export_incentive_effective_date'))

    op.drop_table('government_export_incentive')
    with op.batch_alter_table('geopolitical_risk_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geopolitical_risk_event_as_of_date'))

    op.drop_table('geopolitical_risk_event')
    # ### end Alembic commands ###
