"""add_requires_review_is_bci_yarn

Revision ID: d92251dd65ff
Revises: 0688d6224451
Create Date: 2026-06-09 12:55:55.940910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd92251dd65ff'
down_revision: Union[str, Sequence[str], None] = '0688d6224451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yarn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin_country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('price_per_kg_usd', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('local_currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('fibre_content_pct_cotton', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('fibre_content_pct_polyester', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('fibre_content_pct_modal', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('fibre_content_pct_viscose', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('fibre_content_pct_spandex', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('colour', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_melange', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('is_recycled', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('is_bci', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('requires_review', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('supplier_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('buyer_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('po_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('grn_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('grn_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('quantity_kg', sa.Numeric(precision=12, scale=4), nullable=True))
        batch_op.add_column(sa.Column('po_rate_inr', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('amount_inr', sa.Numeric(precision=12, scale=4), nullable=True))
        batch_op.add_column(sa.Column('dc_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('dc_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('yarn_type_raw', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('as_of_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('data_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yarn', schema=None) as batch_op:
        batch_op.drop_column('data_notes')
        batch_op.drop_column('as_of_date')
        batch_op.drop_column('yarn_type_raw')
        batch_op.drop_column('dc_date')
        batch_op.drop_column('dc_number')
        batch_op.drop_column('amount_inr')
        batch_op.drop_column('po_rate_inr')
        batch_op.drop_column('quantity_kg')
        batch_op.drop_column('grn_date')
        batch_op.drop_column('grn_number')
        batch_op.drop_column('po_number')
        batch_op.drop_column('buyer_reference')
        batch_op.drop_column('supplier_name')
        batch_op.drop_column('requires_review')
        batch_op.drop_column('is_bci')
        batch_op.drop_column('is_recycled')
        batch_op.drop_column('is_melange')
        batch_op.drop_column('colour')
        batch_op.drop_column('fibre_content_pct_spandex')
        batch_op.drop_column('fibre_content_pct_viscose')
        batch_op.drop_column('fibre_content_pct_modal')
        batch_op.drop_column('fibre_content_pct_polyester')
        batch_op.drop_column('fibre_content_pct_cotton')
        batch_op.drop_column('local_currency')
        batch_op.drop_column('price_per_kg_usd')
        batch_op.drop_column('origin_country')

    # ### end Alembic commands ###
